Proposal: Scripting System
vignetteapp/ideas pull request #12
Opened 2022-02-02 03:14 UTC by LeNitrous

2022-02-03 00:19 UTC, sr229 requested changes

2022-02-03 00:19 UTC, sr229 commented on client/proposal-scripting-system.md
> +`<asset-name>:<module-name>.<function-name>`
We can also infer that this could be a method name too unless you plan only to support functions only

2022-02-03 00:19 UTC, sr229 commented on client/proposal-scripting-system.md
> +Localization is optional but preferrable. Scripts may access localized strings defined in its own `lang` directory or the global registry via the localization API:
Re word this to "recommended" since we want to encourage people to invest in localization if their extension goes popular

2022-03-07 04:37 UTC, LeNitrous commented
Closing as the scripting system has been largely changed. A PR will supersede this to cover the changes.

2022-03-07 04:37 UTC, closed without merging